version: '3'

services:
  mongo:
    image: mongo:5.0.3-focal
    container_name: local
    ports:
      - "27017:27017"

  activemq:
    image: rmohr/activemq:5.14.0-alpine
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    
  postgre:
    image: postgres:12.9-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - /home/lelouch-lamperouge/docker/data:/var/lib/postgresql/data

